// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR7Pgo7bGyeAc8wONQEwKCMybwv33sP8g',
    appId: '1:35390605432:web:d0aa2145d60ac94989c58d',
    messagingSenderId: '35390605432',
    projectId: 'fotisia-485cf',
    authDomain: 'fotisia-485cf.firebaseapp.com',
    storageBucket: 'fotisia-485cf.appspot.com',
    measurementId: 'G-R4JSESDJGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZVUTU5DJhbnTsrUsdFfhPfXCBChtVxE0',
    appId: '1:35390605432:android:73ee2291260a477989c58d',
    messagingSenderId: '35390605432',
    projectId: 'fotisia-485cf',
    storageBucket: 'fotisia-485cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHu_yIFv0m1PL9MRm58g5mfRmTgeXIXFo',
    appId: '1:35390605432:ios:18546c1b49bb2fb889c58d',
    messagingSenderId: '35390605432',
    projectId: 'fotisia-485cf',
    storageBucket: 'fotisia-485cf.appspot.com',
    iosClientId: '35390605432-2rcv08cfu4ahtoc3oe1tg4rtovnrjaub.apps.googleusercontent.com',
    iosBundleId: 'com.fotisia.fotisia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHu_yIFv0m1PL9MRm58g5mfRmTgeXIXFo',
    appId: '1:35390605432:ios:162e6e2e653fd81189c58d',
    messagingSenderId: '35390605432',
    projectId: 'fotisia-485cf',
    storageBucket: 'fotisia-485cf.appspot.com',
    iosClientId: '35390605432-8q1giq0dhj49a8ip6sheqfkim272i8db.apps.googleusercontent.com',
    iosBundleId: 'com.example.careerassistant.RunnerTests',
  );
}
