---
apiVersion: v1
kind: Service
metadata:
  name: fotisia-api-service
  labels:
    name: fotisia-api-pod-service
    app: fotisia-api-pod
  namespace: production
spec:
  type: LoadBalancer
  selector:
    name: fotisia-api
    app: fotisia-api-pod
  ports:
    - name: http
      port: 8800
      targetPort: 8800
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fotisia-api
  labels:
    name: fotisia-api-deploy
    app: fotisia-api
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fotisia-api-pod
      app: fotisia
  template:
    metadata:
      name: fotisia-api-pod
      labels:
        name: fotisia-api-pod
        app: fotisia
    spec:
      containers:
      - name: fotisia-container-image
        image: europe-west2-docker.pkg.dev/fotisia-485cf/fotisia-backend/build:latest
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: NODE_ENV
        - name: SERVER_PORT
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: SERVER_PORT
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: DATABASE_HOST
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: DATABASE_PASSWORD
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: DATABASE_NAME
        - name: DATABASE_DIALECT
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: DATABASE_DIALECT
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: DATABASE_PORT
        - name: FORTISIA_GPT_API_BASE_URL
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: FORTISIA_GPT_API_BASE_URL
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: ACCESS_TOKEN_SECRET
        - name: ACCESS_TOKEN_JWT_LIFETIME
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: ACCESS_TOKEN_JWT_LIFETIME
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: SLACK_TOKEN
        - name: SLACK_BUG_REPORT_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: SLACK_BUG_REPORT_CHANNEL_ID
        - name: SLACK_NEW_USER_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: SLACK_NEW_USER_CHANNEL_ID
        - name: AWS_S3_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: AWS_S3_PASSWORD
        - name: AWS_S3_SIGN_URL
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: AWS_S3_SIGN_URL
        - name: AWS_S3_USERNAME
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: AWS_S3_USERNAME
        - name: AWS_S3_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: AWS_S3_PUBLIC_KEY
        - name: AWS_S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: AWS_S3_SECRET_KEY
        - name: GOOGLE_AI_STUDIO_API_KEY
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: GOOGLE_AI_STUDIO_API_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: OPENAI_API_KEY
        - name: GOOGLE_CLOUD_TEXT_TO_SPEECH_API_KEY
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: GOOGLE_CLOUD_TEXT_TO_SPEECH_API_KEY
        - name: NEWS_API_KEY
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: NEWS_API_KEY
        - name: GOOGLE_SEARCH_API_KEY
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: GOOGLE_SEARCH_API_KEY
        - name: GOOGLE_JOB_SEARCH_ENGINE_ID
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: GOOGLE_JOB_SEARCH_ENGINE_ID
        - name: GOOGLE_EVENTS_SEARCH_ENGINE_ID
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: GOOGLE_EVENTS_SEARCH_ENGINE_ID
        - name: GOOGLE_OPPORTUNITIES_SEARCH_ENGINE_ID
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: GOOGLE_OPPORTUNITIES_SEARCH_ENGINE_ID
        - name: GOOGLE_GENERAL_SEARCH_ENGINE_ID
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: GOOGLE_GENERAL_SEARCH_ENGINE_ID
        - name: COMPANY_EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: COMPANY_EMAIL_PASSWORD
        - name: COMPANY_EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: COMPANY_EMAIL_USER
        - name: UDEMY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: UDEMY_CLIENT_ID
        - name: UDEMY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: UDEMY_CLIENT_SECRET
        - name: IMPACT_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: IMPACT_ACCOUNT_SID
        - name: IMPACT_ACCOUNT_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: fotisia-secrets
              key: IMPACT_ACCOUNT_AUTH_TOKEN
